name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . pytest pytest-cov ruff mypy black isort
      - name: Ruff (lint)
        run: ruff check .
      - name: Black (format check)
        run: black --check .
      - name: Isort (import order check)
        run: isort . --check-only --diff
      - name: Mypy (type check)
        run: mypy --python-version ${{ matrix.python-version }} src tests
      - name: Pytest + Coverage
        run: pytest -q --cov=src/hallucination_detector --cov-report=xml --cov-report=term-missing
      - name: Upload coverage to Codecov
        if: ${{ always() }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unit
          fail_ci_if_error: false

  schema:
    name: Schema tests (jsonschema extra)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install with schema extra
        run: |
          python -m pip install --upgrade pip
          pip install -e .[schema] pytest
      - name: Run tests with jsonschema installed
        run: pytest -q
